### ISSUE TITLE
Bug: Defining the field model in Schema definition causes unexpected behavior

### ISSUE THREAD

**Issue by blakedietz** [dynamoosejs/dynamoose#675]
### Summary:

Defining the field `model` for a schema causes unexpected results.

Here's the schema:

https://github.com/blakedietz/dynamoose-model-bug/blob/master/src/models.js#L17

Creating a model from that schema without any parameters yields the following:

```json
{
    "dataKey": "product-undefined",
    "id": "40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "partitionKey": "product-40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "sortKey": "PRODUCT",
    "createdAt": "2019-09-06T22:31:53.298Z",
    "updatedAt": "2019-09-06T22:31:53.298Z",
    "model": "function (modelName) {\n        const { models } = this.$__.base;\n        if (!Object.prototype.hasOwnProperty.call(models, modelName)) {\n            const errorMsg = `Schema hasn't been registered for model \"${modelName}\".\\nUse dynamoose.model(name, schema)`;\n            throw new errors.ModelError(errorMsg);\n        }\n        return models[modelName];\n    }"
}
```

### Code sample:

See the bug in a repo here: https://github.com/blakedietz/dynamoose-model-bug

Run:

```bash
git clone git@github.com:blakedietz/dynamoose-model-bug.git;
npm i;
npm run env:setup;
npm start;

curl -X POST \
  http://localhost:3000/product \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 18' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:3000' \
  -H 'cache-control: no-cache' \
  -d '{
	"product": {}
}'
```

#### Schema
```js
const ProductSchema = new Schema(
  {
    testData: String,
    dataKey: {
      type: String,
      default: model =>
        `product-${model.id}`
    },
    id: {
      type: String,
      default: uuid
    },
    model: String,
    partitionKey: {
      type: String,
      hashKey: true,
      default: model => `product-${model.id}`
    },
    sortKey: {
      type: String,
      index: {
        global: true,
        name: "globalSecondaryIndex-1",
        rangeKey: "dataKey",
        project: true
      },
      default: "PRODUCT"
    },
  },
  {
    timestamps: true
  }
);

```

#### Model
```js
const ProductModel = dynamoose.model(
  'Product',
  ProductSchema,
  {
    tableName: process.env.DYNAMODB_TABLE
  }
);
```

#### General
```js
    const newProduct = await ProductModel.create({});
```

### Current output and behavior:

```json
{
    "dataKey": "product-undefined",
    "id": "40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "partitionKey": "product-40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "sortKey": "PRODUCT",
    "createdAt": "2019-09-06T22:31:53.298Z",
    "updatedAt": "2019-09-06T22:31:53.298Z",
    "model": "function (modelName) {\n        const { models } = this.$__.base;\n        if (!Object.prototype.hasOwnProperty.call(models, modelName)) {\n            const errorMsg = `Schema hasn't been registered for model \"${modelName}\".\\nUse dynamoose.model(name, schema)`;\n            throw new errors.ModelError(errorMsg);\n        }\n        return models[modelName];\n    }"
}
```

### Expected output and behavior:

```json
{
    "dataKey": "product-undefined",
    "id": "40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "partitionKey": "product-40d42876-a6c7-4e19-ae06-357f1c9d9e72",
    "sortKey": "PRODUCT",
    "createdAt": "2019-09-06T22:31:53.298Z",
    "updatedAt": "2019-09-06T22:31:53.298Z",
    "model": ""
}
```

### Environment:

Operating System: macOS
Operating System Version: 10.14.5 (18F132)
Node.js version (`node -v`): 10.16.0
NPM version: (`npm -v`): 6.10.0
Dynamoose version: 1.11.1
Dynamoose Plugins:
n/a

### Dynamoose Plugins:

- [ ] Yes, I believe that one or multiple 3rd party Dynamoose plugins are effecting this issue
- [ ] No, I believe this issue is independent of any 3rd party Dynamoose plugins I'm using
- [ ] Unknown, I'm unsure if Dynamoose plugins are effecting this issue
- [x] I am not using any Dynamoose plugins

### Type (select 1):
- [x] Bug report
- [ ] Feature suggestion
- [x] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
This only exists if you name a property in your schema “model”, correct?

**Comment by blakedietz** [comment]
Yes

**Comment by fishcharlie** [comment]
This MIGHT be fixed in v2.0 rewrite. But highly doubtful this will be fixed in 1.x. Pretty easy to work around this, so not considered a high priority issue.

**Comment by fishcharlie** [comment]
@blakedietz Wanna give this a try in beta 1 of version 2.0? I think it should be working better now. Might be worth it to create a test case as well for this at some point.

**Comment by fishcharlie** [comment]
Closing this due to no recent activity. If this is still a problem or you have questions please feel free to comment again and we can try to help further.

**Comment by hardikbeladiya** [comment]
This is Still Happening as was having the same Field in my Schema and my Version of Dynamoose is : "dynamoose": "^2.3.0"

**Comment by fishcharlie** [comment]
Duplicate of #1023
